Repository googleapis/jsdoc-fresh, pull requests merged in 2020-07, with the labels that each got.

#22 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#23 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#26 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#25 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#31 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#29 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  synth.metadata
Labels: cla: yes, context: none

#30 chore: add config files for cloud-rad, delete template for Node 8 tests
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#32 build: correct dev-site config
  .gitattributes
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full
