Repository googleapis/jsdoc-fresh, pull requests merged in 2021-05, with the labels that each got.

#61 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#63 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#66 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .repo-metadata.json
  owlbot.py
  synth.metadata
  synth.py
Labels: cla: yes
